"""Version 2 behavioral platform for rollout post-processing.

The package is additive to the frozen v1 implementation. It operates on
already-produced rollout arrays and does not run FlyGym/MuJoCo simulations,
modify controllers, or introduce perturbations.
"""

from drosophila_pd.behavior_platform.comparison import (
    ComparisonCondition,
    ComparisonPlaybackPlan,
    build_comparison_playback_plan,
    compare_rollouts,
)
from drosophila_pd.behavior_platform.behavior_comparison import compare_behavior_conditions
from drosophila_pd.behavior_platform.advanced_visualization import (
    VISUAL_EXPORT_FORMATS,
    export_advanced_visualization_set,
    export_replay_dashboard,
    plot_behavioral_embeddings,
    plot_behavioral_network_graph,
    plot_behavioral_state_timeline,
    plot_intervention_timeline,
    plot_progression_map,
    plot_radar_plot,
    plot_sankey_transition_diagram,
    plot_similarity_heatmap,
    plot_trajectory_clusters,
)
from drosophila_pd.behavior_platform.dashboard import (
    DASHBOARD_EXPORT_FORMATS,
    build_behavior_dashboard,
    export_behavior_dashboard,
    plot_trajectory_explorer,
)
from drosophila_pd.behavior_platform.data_model import (
    Arena,
    ArenaZone,
    BehaviorComparison,
    BehaviorDashboard,
    BehaviorEpisode,
    BehaviorReport,
    BehaviorSequence,
    ProgressionStage,
    ProgressionTimeline,
)
from drosophila_pd.behavior_platform.digital_twin import (
    DIGITAL_TWIN_SCOPE,
    DigitalTwin,
    TwinConfiguration,
    TwinHistory,
    TwinMetadata,
    TwinReplay,
    TwinScenario,
    TwinSnapshot,
    TwinState,
)
from drosophila_pd.behavior_platform.export import (
    ExportRequest,
    RolloutExportResult,
    export_rollout_package,
)
from drosophila_pd.behavior_platform.gait import (
    CANONICAL_LEG_ORDER,
    GaitAnalysisConfig,
    GaitInput,
    analyze_gait,
)
from drosophila_pd.behavior_platform.gait_animation import (
    GaitAnimationRequest,
    GaitAnimationResult,
    render_gait_animation,
)
from drosophila_pd.behavior_platform.gait_export import (
    GaitExportRequest,
    GaitExportResult,
    export_gait_package,
)
from drosophila_pd.behavior_platform.gait_visualization import (
    plot_contact_raster,
    plot_coordination_matrix,
    plot_foot_trajectories,
    plot_footfall_diagram,
    plot_gait_timeline,
    plot_joint_trajectories,
    plot_phase_wheel,
    plot_stride_plot,
    render_gait_visualization_set,
)
from drosophila_pd.behavior_platform.intervention import (
    INTERVENTION_SCOPE,
    InterventionDefinition,
    InterventionTimeline,
    ParameterSchedule,
    StagedIntervention,
    apply_intervention_parameters,
    compare_intervention_reports,
    intervention_from_config,
    intervention_to_json,
    replay_intervention,
)
from drosophila_pd.behavior_platform.lab import (
    ExperimentCatalog,
    ExperimentRecord,
    LabLayout,
    build_experiment_catalog,
    build_interactive_lab,
    load_lab_layout,
    save_lab_layout,
)
from drosophila_pd.behavior_platform.measurement import (
    DEFAULT_BEHAVIOR_MEASUREMENT_CONFIG,
    measure_rollout_behavior,
)
from drosophila_pd.behavior_platform.open_field import (
    analyze_open_field,
    export_open_field_report,
)
from drosophila_pd.behavior_platform.progression import (
    interpolate_stages,
    interpolated_stage_at,
    progression_from_config,
    progression_to_json,
    replay_progression,
    stage_at,
)
from drosophila_pd.behavior_platform.rendering import (
    OfflineRenderRequest,
    OfflineRenderResult,
    render_offline,
)
from drosophila_pd.behavior_platform.rollout import RolloutData
from drosophila_pd.behavior_platform.scenario import (
    ScenarioDefinition,
    ScenarioResult,
    batch_execute_scenarios,
    build_scenario,
    compare_scenarios,
    scenario_report_to_json,
)
from drosophila_pd.behavior_platform.state_machine import (
    DEFAULT_STATES,
    BehaviorStateMachineConfig,
    analyze_state_sequence,
    classify_behavior_states,
    reconstruct_state_timeline,
)
from drosophila_pd.behavior_platform.visualization import (
    CameraPreset,
    ViewerPlan,
    build_viewer_plan,
)
from drosophila_pd.behavior_platform.video_system import (
    VIDEO_EXPORT_FORMATS,
    PlaybackOverlayConfig,
    SynchronizedPlaybackRequest,
    SynchronizedPlaybackResult,
    render_synchronized_playback,
)

__all__ = [
    "Arena",
    "ArenaZone",
    "BehaviorComparison",
    "BehaviorDashboard",
    "BehaviorEpisode",
    "BehaviorReport",
    "BehaviorSequence",
    "CameraPreset",
    "ComparisonCondition",
    "ComparisonPlaybackPlan",
    "DASHBOARD_EXPORT_FORMATS",
    "DEFAULT_STATES",
    "DEFAULT_BEHAVIOR_MEASUREMENT_CONFIG",
    "DIGITAL_TWIN_SCOPE",
    "CANONICAL_LEG_ORDER",
    "DigitalTwin",
    "ExperimentCatalog",
    "ExperimentRecord",
    "ExportRequest",
    "GaitAnalysisConfig",
    "GaitAnimationRequest",
    "GaitAnimationResult",
    "GaitExportRequest",
    "GaitExportResult",
    "GaitInput",
    "INTERVENTION_SCOPE",
    "InterventionDefinition",
    "InterventionTimeline",
    "LabLayout",
    "OfflineRenderRequest",
    "OfflineRenderResult",
    "ParameterSchedule",
    "PlaybackOverlayConfig",
    "ProgressionStage",
    "ProgressionTimeline",
    "RolloutData",
    "RolloutExportResult",
    "ScenarioDefinition",
    "ScenarioResult",
    "StagedIntervention",
    "SynchronizedPlaybackRequest",
    "SynchronizedPlaybackResult",
    "TwinConfiguration",
    "TwinHistory",
    "TwinMetadata",
    "TwinReplay",
    "TwinScenario",
    "TwinSnapshot",
    "TwinState",
    "VISUAL_EXPORT_FORMATS",
    "VIDEO_EXPORT_FORMATS",
    "ViewerPlan",
    "analyze_state_sequence",
    "analyze_gait",
    "analyze_open_field",
    "apply_intervention_parameters",
    "batch_execute_scenarios",
    "build_behavior_dashboard",
    "build_comparison_playback_plan",
    "build_experiment_catalog",
    "build_interactive_lab",
    "build_scenario",
    "build_viewer_plan",
    "compare_behavior_conditions",
    "compare_intervention_reports",
    "compare_rollouts",
    "compare_scenarios",
    "classify_behavior_states",
    "export_advanced_visualization_set",
    "export_behavior_dashboard",
    "export_gait_package",
    "export_open_field_report",
    "export_replay_dashboard",
    "export_rollout_package",
    "interpolate_stages",
    "interpolated_stage_at",
    "intervention_from_config",
    "intervention_to_json",
    "load_lab_layout",
    "measure_rollout_behavior",
    "plot_behavioral_embeddings",
    "plot_behavioral_network_graph",
    "plot_behavioral_state_timeline",
    "plot_contact_raster",
    "plot_coordination_matrix",
    "plot_foot_trajectories",
    "plot_footfall_diagram",
    "plot_gait_timeline",
    "plot_joint_trajectories",
    "plot_phase_wheel",
    "plot_progression_map",
    "plot_radar_plot",
    "plot_sankey_transition_diagram",
    "plot_similarity_heatmap",
    "plot_stride_plot",
    "plot_trajectory_explorer",
    "plot_trajectory_clusters",
    "progression_from_config",
    "progression_to_json",
    "reconstruct_state_timeline",
    "render_synchronized_playback",
    "render_gait_animation",
    "render_gait_visualization_set",
    "render_offline",
    "replay_intervention",
    "replay_progression",
    "save_lab_layout",
    "scenario_report_to_json",
    "stage_at",
]
